import React from 'react';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import axios from 'axios';
import Panel from './PaperOrderIntentPanel';
import { submitPaperOrder, getLatestPaperRequest } from '../utils/paperOrderRequest';
beforeAll(() => { Object.defineProperty(window, 'crypto', { value: require('crypto').webcrypto, configurable: true }); });
beforeEach(() => { sessionStorage.clear(); jest.clearAllMocks(); });
const payload = { symbol: 'SPY', side: 'buy', qty: 1, orderType: 'limit', limitPrice: 100 };
test('new identical order requires terminal refresh then separate prepare and submit actions', async () => {
  axios.post.mockResolvedValue({ data: { executionSource: 'alpaca-paper', order: { status: 'acknowledged', filledQty: 0 } } });
  await submitPaperOrder(payload);
  const record = getLatestPaperRequest('stock');
  axios.get.mockResolvedValue({ data: [{ idempotencyKey: record.key, status: 'acknowledged' }] });
  render(<Panel surface="stock" symbol="SPY" />);
  expect(screen.getByRole('button', { name: 'Prepare another identical order' })).toBeDisabled();
  await waitFor(() => expect(axios.get).toHaveBeenCalledTimes(1));
  axios.get.mockResolvedValue({ data: [{ idempotencyKey: record.key, status: 'filled', filledQty: 1 }] });
  fireEvent.click(screen.getByRole('button', { name: 'Refresh order status' }));
  await waitFor(() => expect(screen.getByRole('button', { name: 'Prepare another identical order' })).toBeEnabled());
  fireEvent.click(screen.getByRole('button', { name: 'Prepare another identical order' }));
  expect(axios.post).toHaveBeenCalledTimes(1);
  await waitFor(() => expect(screen.getByRole('button', { name: 'Submit prepared order' })).toBeEnabled());
  fireEvent.click(screen.getByRole('button', { name: 'Submit prepared order' }));
  await waitFor(() => expect(axios.post).toHaveBeenCalledTimes(2));
  expect(axios.post.mock.calls[0][2].headers['Idempotency-Key']).not.toBe(axios.post.mock.calls[1][2].headers['Idempotency-Key']);
});
test('uncertain reload recovers stored ticket and retry uses its unchanged key', async () => {
  axios.post.mockRejectedValueOnce(new Error('timeout')).mockResolvedValue({ data: { order: { status: 'submission_uncertain' } } });
  await expect(submitPaperOrder(payload)).rejects.toThrow();
  axios.get.mockResolvedValue({ data: [] });
  const view = render(<Panel surface="stock" symbol="SPY" />);
  await screen.findByRole('alert');
  view.unmount();
  render(<Panel surface="stock" symbol="SPY" />);
  expect(screen.getByRole('button', { name: 'Prepare another identical order' })).toBeDisabled();
  fireEvent.click(screen.getByRole('button', { name: 'Retry same order' }));
  await waitFor(() => expect(axios.post).toHaveBeenCalledTimes(2));
  expect(axios.post.mock.calls[0][2].headers['Idempotency-Key']).toBe(axios.post.mock.calls[1][2].headers['Idempotency-Key']);
});
