const test=require('node:test');const assert=require('node:assert/strict');const crypto=require('node:crypto');const mongoose=require('mongoose');
const {createOrderLifecycle}=require('../services/orderLifecycleService');
const Intent=require('../models/OrderIntent'),BrokerOrder=require('../models/BrokerOrder'),Fill=require('../models/Fill'),Bucket=require('../models/SpendingBucket'),Capacity=require('../models/AccountCapacity');
const ownerId='507f1f77bcf86cd799439011';
const settings={mode:'paper',isEnabled:true,dailyLimit:100,weeklyLimit:200,monthlyLimit:300};
function fixture(options={}){let calls=0;const orders=new Map();const broker={mode:'paper',getAccount:async()=>({id:'test-paper',cash:'1000.00'}),getAsset:async()=>({tradable:true,class:'us_equity',status:'active'}),getPositions:async()=>[{symbol:'AAPL',qty:'100',qty_available:'100'}],submitOrder:async x=>{calls++;const o={id:crypto.randomUUID(),client_order_id:x.clientOrderId,symbol:x.symbol,side:x.side,qty:String(x.qty),filled_qty:'0',status:'new'};orders.set(o.client_order_id,o);if(options.timeout)throw new Error('accepted timeout');return {order:o};},getOrderByClientOrderId:async id=>{const o=orders.get(id);if(!o||options.miss)throw Object.assign(new Error('not found'),{status:404,response:{status:404}});return o;},getOrder:async id=>[...orders.values()].find(o=>o.id===id),cancelOrder:async id=>{[...orders.values()].find(o=>o.id===id).status='canceled';},replaceOrder:async(id,x)=>{const old=[...orders.values()].find(o=>o.id===id);old.status='replaced';const o={...old,id:crypto.randomUUID(),client_order_id:x.client_order_id,qty:String(x.qty),status:'new',replaces:id};old.replaced_by=o.id;orders.set(o.client_order_id,o);if(options.replaceTimeout)throw new Error('replace timeout');return o;}};
return {broker,orders,get calls(){return calls},service:()=>createOrderLifecycle({broker,ownerId,expectedAccountId:'test-paper',loadSettings:async()=>settings,...options})};}
const request=(key='one',origin='manual',qty=6)=>({userId:ownerId,idempotencyKey:key,origin,orderInput:{symbol:'AAPL',side:'buy',qty,orderType:'limit',limitPrice:10}});
test('real replica-set financial lifecycle',async t=>{
 const uri=`mongodb://127.0.0.1:27189/mvp_test_lifecycle_${crypto.randomUUID().replaceAll('-','')}?replicaSet=mvp&directConnection=true`;const u=new URL(uri);if(!['127.0.0.1','localhost'].includes(u.hostname)||!/^\/mvp_test[_-]/.test(u.pathname))throw new Error('Disposable loopback mvp_test database required');
 await mongoose.connect(uri,{serverSelectionTimeoutMS:3000});
 try{await Promise.all([Intent,BrokerOrder,Fill,Bucket,Capacity].map(m=>m.init()));
 const reset=()=>Promise.all([Intent,BrokerOrder,Fill,Bucket,Capacity].map(m=>m.deleteMany({})));
 await t.test('manual/manual, robo/robo and mixed races admit exactly one',async()=>{for(const origins of [['manual','manual'],['robo','robo'],['manual','robo']]){await reset();const f=fixture(),s=f.service();const out=await Promise.allSettled([s.submit(request('a',origins[0])),s.submit(request('b',origins[1]))]);assert.equal(out.filter(x=>x.status==='fulfilled').length,1);assert.equal(f.calls,1);assert.equal((await Capacity.findOne()).reservedCents,6000);}});
 await t.test('duplicate concurrent submit and fingerprint conflict',async()=>{await reset();const f=fixture(),s=f.service();await Promise.all([s.submit(request()),s.submit(request())]);assert.equal(f.calls,1);await assert.rejects(s.submit(request('one','manual',5)),/conflict/);});
 await t.test('accepted timeout misses and restart never resubmit',async()=>{await reset();const f=fixture({timeout:true,miss:true});let out=await f.service().submit(request());assert.equal(out.intent.status,'submission_uncertain');await f.service().reconcile({intentId:out.intent._id});await f.service().submit(request());assert.equal(f.calls,1);assert.equal((await Capacity.findOne()).reservedCents,6000);});
 await t.test('post-acceptance persistence failure recovers original',async()=>{await reset();const f=fixture({afterBrokerSubmit:async()=>{throw new Error('database save failure')}});let out=await f.service().submit(request());assert.equal(out.intent.status,'submission_uncertain');out=await f.service().reconcile({intentId:out.intent._id});assert.equal(out.intent.status,'acknowledged');assert.equal(f.calls,1);});
 await t.test('partial fill duplicate/out-of-order then canceled releases only remainder',async()=>{await reset();const f=fixture(),s=f.service();const out=await s.submit(request());const raw=[...f.orders.values()][0];raw.filled_qty='4';raw.filled_avg_price='9.50';raw.status='partially_filled';await s.reconcile({intentId:out.intent._id});await s.reconcile({intentId:out.intent._id});assert.equal(await Fill.countDocuments(),1);assert.equal((await Capacity.findOne()).reservedCents,2200);raw.filled_qty='2';raw.filled_avg_price='9.50';await s.reconcile({intentId:out.intent._id});assert.equal(await Fill.countDocuments(),1);raw.filled_qty='4';await s.cancel({intentId:out.intent._id});assert.equal((await Capacity.findOne()).reservedCents,0);assert.equal((await Bucket.findOne({period:'day'})).spentCents,3800);});
 await t.test('pre-submit control rejection releases reservation without POST',async()=>{await reset();const f=fixture(),s=f.service();await assert.rejects(s.submit({...request(),beforeSubmit:async()=>{throw new Error('disabled')}}),/disabled/);assert.equal(f.calls,0);assert.equal((await Capacity.findOne()).reservedCents,0);assert.equal((await Intent.findOne()).status,'rejected');});
 await t.test('definitive rejected entry releases and 5xx replacement retains conservative capacity',async()=>{await reset();let f=fixture();f.broker.submitOrder=async()=>{throw Object.assign(new Error('invalid order'),{response:{status:422}})};let out=await f.service().submit(request());assert.equal(out.intent.status,'rejected');assert.equal((await Capacity.findOne()).reservedCents,0);await reset();f=fixture({replaceTimeout:true});out=await f.service().submit(request());out=await f.service().replace({intentId:out.intent._id,idempotencyKey:'replacement',changes:{qty:5}});assert.equal(out.intent.status,'replace_pending');assert.equal((await Capacity.findOne()).reservedCents,6000);await f.service().reconcile({intentId:out.intent._id});assert.equal(await BrokerOrder.countDocuments(),2);});
 await t.test('replacement rejection keeps original live and retains original capacity',async()=>{await reset();const f=fixture(),s=f.service();let out=await s.submit(request());f.broker.replaceOrder=async()=>{throw Object.assign(new Error('replacement invalid'),{response:{status:422}})};out=await s.replace({intentId:out.intent._id,idempotencyKey:'reject',changes:{qty:5}});assert.equal(out.intent.status,'acknowledged');assert.equal((await Capacity.findOne()).reservedCents,6000);await s.cancel({intentId:out.intent._id});assert.equal((await Capacity.findOne()).reservedCents,0);});
 await t.test('weekly and monthly limits bind concurrent requests independently',async()=>{for(const field of ['weeklyLimit','monthlyLimit']){await reset();const f=fixture({loadSettings:async()=>({...settings,dailyLimit:1000,weeklyLimit:1000,monthlyLimit:1000,[field]:100})}),service=f.service();const out=await Promise.allSettled([service.submit(request('weekly-a')),service.submit(request('weekly-b','robo'))]);assert.equal(out.filter(x=>x.status==='fulfilled').length,1);assert.equal(f.calls,1);}});
 await t.test('old-period uncertainty remains counted in fresh day/week/month',async()=>{await reset();let instant=new Date('2026-08-31T12:00:00Z');const f=fixture({timeout:true,miss:true,now:()=>instant}),service=f.service();await service.submit(request('old'));instant=new Date('2026-10-05T12:00:00Z');await assert.rejects(service.submit(request('new')),/spending limit/);assert.equal(f.calls,1);assert.equal((await Capacity.findOne()).reservedCents,6000);});
 await t.test('reducing exit bypasses exhausted spending and daily loss thresholds',async()=>{await reset();const f=fixture({loadSettings:async()=>({...settings,dailyLimit:0,weeklyLimit:0,monthlyLimit:0,maxDailyLoss:1})});f.broker.getAccount=async()=>({id:'test-paper',cash:'0.00',equity:'50.00',last_equity:'100.00'});const out=await f.service().submit({...request('exit'),orderInput:{symbol:'AAPL',side:'sell',qty:2,orderType:'market'}});assert.equal(out.intent.status,'acknowledged');assert.equal(f.calls,1);assert.equal((await Capacity.findOne()).reservedCents,0);});
 await t.test('production factory requires positive complete risk settings by default',async()=>{
  await reset();
  const {executionReadiness}=require('../services/executionReadiness');
  await executionReadiness.bootstrap(async()=>[{ok:true}],async()=>{});
  const {getOrderLifecycle}=require('../services/orderLifecycleService');
  const f=fixture();
  const make=loadSettings=>getOrderLifecycle({broker:f.broker,ownerId,expectedAccountId:'test-paper',loadSettings});
  await assert.rejects(make(async()=>({...settings,maxTradeAmount:0})).submit(request('invalid-limit')),/Currency/);
  assert.equal(f.calls,0);
  const configured={...settings,maxTradeAmount:100,maxPositionSize:1000,maxDailyLoss:100,maxOpenPositions:5,maxTradesPerDay:3};
  await assert.rejects(make(async()=>configured).submit(request('incomplete-account')),/account risk context/);
  assert.equal(f.calls,0);
  f.broker.getAccount=async()=>({id:'test-paper',cash:'1000.00',status:'ACTIVE',equity:'1000.00',last_equity:'1000.00'});
  f.broker.getPositions=async()=>[];
  for(const key of ['invalid-limit','incomplete-account']){
   const retry=await make(async()=>configured).submit(request(key));
   assert.equal(retry.intent.status,'rejected');
   assert.equal(retry.intent.reservedCents,0);
   assert.equal(f.calls,0);
  }
  const out=await make(async()=>configured).submit(request('valid-risk-context'));
  assert.equal(out.intent.status,'acknowledged');
  assert.equal(f.calls,1);
 });
 await t.test('uncertain, submitting and rejected local states have durable outbox events',async()=>{await reset();const Outbox=require('../models/NotificationOutbox');const f=fixture({timeout:true,miss:true});const out=await f.service().submit(request('audit'));for(const status of ['reserved','submitting','submission_uncertain'])assert.ok(await Outbox.exists({eventKey:`lifecycle:${out.intent._id}:${status}:0`}));const g=fixture();await assert.rejects(g.service().submit({...request('blocked','manual',2),beforeSubmit:async()=>{throw new Error('stop')}}));const rejected=await Intent.findOne({idempotencyKey:'blocked'});assert.ok(await Outbox.exists({eventKey:`lifecycle:${rejected._id}:rejected:0`}));});
 await t.test('final lease/control callback prevents POST after intervening protection check',async()=>{await reset();let allowed=true,protectionChecks=0,controlChecks=0;const f=fixture({beforeEntry:async()=>{if(++protectionChecks===2)allowed=false;}});await assert.rejects(f.service().submit({...request('lease-lost','robo'),beforeSubmit:async()=>{controlChecks++;if(!allowed)throw new Error('worker lease lost');}}),/worker lease lost/);assert.equal(protectionChecks,2);assert.equal(controlChecks,2);assert.equal(f.calls,0);assert.equal((await Capacity.findOne()).reservedCents,0);assert.equal((await Intent.findOne()).status,'rejected');});
 await t.test('partial fill replacement binds cumulative chain without double charging',async()=>{await reset();const f=fixture(),s=f.service();const out=await s.submit(request());const raw=[...f.orders.values()][0];Object.assign(raw,{filled_qty:'2',filled_avg_price:'10.00',status:'partially_filled'});await s.reconcile({intentId:out.intent._id});await s.replace({intentId:out.intent._id,idempotencyKey:'r1',changes:{qty:5}});const successor=[...f.orders.values()][1];Object.assign(successor,{filled_qty:'5',filled_avg_price:'10.00',status:'filled'});await s.reconcile({intentId:out.intent._id});assert.equal((await Bucket.findOne({period:'day'})).spentCents,5000);assert.equal((await Capacity.findOne()).reservedCents,0);assert.equal(await BrokerOrder.countDocuments(),2);});
 }finally{await mongoose.connection.dropDatabase();await mongoose.disconnect();}
});
