const test = require('node:test');
const assert = require('node:assert/strict');
const { randomUUID } = require('node:crypto');
const mongoose = require('mongoose');
const { createOrderLifecycle } = require('../services/orderLifecycleService');
const Intent = require('../models/OrderIntent');
const Capacity = require('../models/AccountCapacity');
const Bucket = require('../models/SpendingBucket');
const Protection = require('../models/OrderProtection');
const Lock = require('../models/OrderProtectionLock');
const Close = require('../models/PositionClose');
const {createOrderProtection} = require('../services/orderProtectionService');
const ownerId = '507f1f77bcf86cd799439011';
test('Phase 3 real Mongo cash and coordinated closes', async t => {
 await mongoose.connect(`mongodb://127.0.0.1:27189/mvp_test_phase3financial_${randomUUID().replaceAll('-', '')}?replicaSet=mvp&directConnection=true`);
 await Promise.all([Intent, Capacity, Bucket, Protection, Lock, Close].map(m => m.init()));
 let sequence = 0;
 async function fixture() {
  const accountId = `financial-${++sequence}`;
  let cash = '100.00', position = 4, cancelConfirmed = true;
  const orders = new Map(), writes = [];
  const broker = { mode:'paper', getAccount:async()=>({id:accountId,cash}),
   getPositions:async()=>[{symbol:'AAPL',qty:String(position),qty_available:String(position)}],
   getAsset:async()=>({tradable:true,class:'us_equity',status:'active'}),
   listOrders:async()=>[...orders.values()].filter(o=>!['filled','canceled','rejected'].includes(o.status)),
   getOrder:async id=>orders.get(id),getOrderByClientOrderId:async id=>[...orders.values()].find(o=>o.client_order_id===id),
   cancelOrder:async id=>{writes.push(['cancel',id]);if(cancelConfirmed)orders.get(id).status='canceled';},
   submitOrder:async input=>{writes.push(['submit',input.qty]);const o={id:randomUUID(),client_order_id:input.clientOrderId,symbol:input.symbol,side:input.side,qty:String(input.qty),filled_qty:'0',status:'new',type:input.orderType,stop_price:input.stopPrice};orders.set(o.id,o);return {order:o};}
  };
  const service=()=>createOrderLifecycle({broker,ownerId,expectedAccountId:accountId,loadSettings:async()=>({mode:'paper',dailyLimit:1000,weeklyLimit:1000,monthlyLimit:1000})});
  const buy=key=>({userId:ownerId,idempotencyKey:key,orderInput:{symbol:'AAPL',side:'buy',qty:6,orderType:'limit',limitPrice:10}});
  const close=()=>({userId:ownerId,idempotencyKey:'close-one',symbol:'AAPL'});
  async function stop() {const entry=await Intent.create({userId:ownerId,accountId,environment:'paper',executionSource:'alpaca-paper',idempotencyKey:'entry',symbol:'AAPL',side:'buy',qty:4,filledQty:4,status:'filled',origin:'manual',broker:'alpaca',orderInput:{stopLossPrice:9}});const o={id:'stop-one',client_order_id:'robo-stop-owned',symbol:'AAPL',side:'sell',type:'stop',qty:'4',filled_qty:'0',status:'new',stop_price:'9'};orders.set(o.id,o);await Protection.create({intentId:entry._id,accountId,userId:ownerId,symbol:'AAPL',state:'protected',qty:4,confirmedQty:4,brokerOrderId:o.id,clientOrderId:o.client_order_id});return o;}
  return {accountId,broker,service,buy,close,stop,orders,writes,setCash:v=>cash=v,setPosition:v=>position=v,setCancel:v=>cancelConfirmed=v};
 }
 try {
  await t.test('confirmed sale/deposit refresh preserves spending, repeated refresh never credits twice',async()=>{
   const f=await fixture(),s=f.service();const out=await s.submit(f.buy('buy'));const raw=[...f.orders.values()][0];Object.assign(raw,{status:'filled',filled_qty:'6',filled_avg_price:'10.00'});await s.reconcile({intentId:out.intent._id});f.setCash('100.00');
   await s.synchronizeCash();await s.synchronizeCash();assert.equal((await Bucket.findOne({accountId:f.accountId,period:'day'})).spentCents,6000);
   const races=await Promise.allSettled([s.submit(f.buy('next-a')),s.submit(f.buy('next-b')),s.synchronizeCash()]);assert.equal(races.slice(0,2).filter(r=>r.status==='fulfilled').length,1);assert.equal(f.writes.length,2);
  });
  await t.test('unresolved entry blocks refresh and invalid/withdrawn cash prevents entry',async()=>{const f=await fixture(),s=f.service();await s.submit(f.buy('a'));await assert.rejects(s.synchronizeCash(),/unresolved/i);f.setCash('0.00');await assert.rejects(s.submit(f.buy('b')),/cash/i);f.setCash('NaN');await assert.rejects(s.synchronizeCash());assert.equal(f.writes.length,1);});
  await t.test('close cancels only app stop, waits for terminal evidence, then sizes actual position',async()=>{const f=await fixture();await f.stop();f.setCancel(false);let out=await f.service().closePosition(f.close());assert.equal(out.close.state,'cancel_pending');assert.deepEqual(f.writes,[['cancel','stop-one']]);f.setPosition(2);f.orders.get('stop-one').status='canceled';out=await f.service().closePosition(f.close());assert.equal(out.intent.qty,2);assert.deepEqual(f.writes,[['cancel','stop-one'],['submit',2]]);await f.service().closePosition(f.close());assert.equal(f.writes.length,2);});
  await t.test('unrelated exit never canceled and blocks full close',async()=>{const f=await fixture();await f.stop();f.orders.set('unrelated',{id:'unrelated',symbol:'AAPL',side:'sell',type:'limit',qty:'1',filled_qty:'0',status:'new'});const out=await f.service().closePosition(f.close());assert.equal(out.close.state,'blocked');assert.equal(f.writes.length,0);});
  await t.test('concurrent close requests share protection lease and submit once',async()=>{const f=await fixture();await f.stop();const results=await Promise.allSettled([f.service().closePosition(f.close()),f.service().closePosition(f.close())]);assert.ok(results.some(r=>r.status==='fulfilled'));await f.service().closePosition(f.close());assert.equal(f.writes.filter(w=>w[0]==='submit').length,1);});
  await t.test('expired close relinquishes protection suppression and does not submit later',async()=>{const f=await fixture();await f.stop();f.setCancel(false);const out=await f.service().closePosition(f.close());f.orders.get('stop-one').status='canceled';await Close.updateOne({_id:out.close._id},{$set:{deadlineAt:new Date(0)}});const expired=await f.service().closePosition(f.close());assert.equal(expired.close.state,'reconciliation_required');assert.equal(expired.close.active,false);assert.equal(f.writes.filter(w=>w[0]==='submit').length,0);const protection=createOrderProtection({broker:f.broker,ownerId,expectedAccountId:f.accountId});await protection.reconcile({intentId:(await Protection.findOne({accountId:f.accountId})).intentId});assert.equal(f.writes.filter(w=>w[0]==='submit').length,1);await f.service().closePosition(f.close());assert.equal(f.writes.filter(w=>w[0]==='cancel').length,1);});
  await t.test('pending close blocks independent manual sell even after stops cancel',async()=>{const f=await fixture();await f.stop();f.setCancel(false);await f.service().closePosition(f.close());await Protection.updateMany({accountId:f.accountId},{$set:{state:'close_pending',confirmedQty:0}});await assert.rejects(f.service().submit({userId:ownerId,idempotencyKey:'other-sell',orderInput:{symbol:'AAPL',side:'sell',qty:1,orderType:'market'}}),/close/i);assert.equal(f.writes.filter(w=>w[0]==='submit').length,0);});
  await t.test('stale cash snapshot and external pending buy cannot refresh capacity',async()=>{const f=await fixture();f.broker.getAccount=async()=>({id:f.accountId,cash:'100.00',timestamp:'2000-01-01T00:00:00Z'});await assert.rejects(f.service().synchronizeCash(),/Fresh/);await assert.rejects(f.service().submit(f.buy('stale')),/Fresh/);f.broker.getAccount=async()=>({id:f.accountId,cash:'100.00'});f.orders.set('external',{id:'external',symbol:'AAPL',side:'buy',qty:'1',status:'new'});await assert.rejects(f.service().synchronizeCash(),/broker.*entr/i);});
  await t.test('accepted close timeout survives service restart and never repeats POST',async()=>{const f=await fixture();await f.stop();const submit=f.broker.submitOrder;f.broker.submitOrder=async input=>{await submit(input);throw new Error('accepted then timeout');};let out=await f.service().closePosition(f.close());assert.equal(out.close.state,'submission_uncertain');out=await f.service().closePosition(f.close());assert.equal(out.close.state,'acknowledged');assert.equal(f.writes.filter(w=>w[0]==='submit').length,1);const sell=[...f.orders.values()].find(o=>o.type==='market');Object.assign(sell,{status:'filled',filled_qty:sell.qty,filled_avg_price:'10.00'});f.setPosition(0);out=(await f.service().resumeCloses())[0];assert.equal(out.close.state,'filled');assert.equal(out.close.active,false);});
  await t.test('lease loss after stop discovery prevents broker cancellation',async()=>{const f=await fixture();await f.stop();const list=f.broker.listOrders;f.broker.listOrders=async()=>{const result=await list();await Lock.updateOne({accountId:f.accountId},{$set:{owner:'other-worker',expiresAt:new Date(Date.now()+60000)}});return result;};const out=await f.service().closePosition(f.close());assert.equal(out.close.state,'cancel_uncertain');assert.match(out.close.error,/lease lost/i);assert.equal(f.writes.length,0);});
  await t.test('unknown stop identity fails safely without cancel or close writes',async()=>{const f=await fixture();await f.stop();f.broker.getOrder=async()=>({id:'stop-one',client_order_id:'someone-else',symbol:'AAPL',side:'sell',type:'stop',status:'new'});const out=await f.service().closePosition(f.close());assert.equal(out.close.state,'cancel_uncertain');assert.equal(f.writes.length,0);});
  await t.test('unfilled close deadline cancels its own exit and returns remaining position to protection',async()=>{const f=await fixture();await f.stop();const first=await f.service().closePosition(f.close());await Close.updateOne({_id:first.close._id},{$set:{deadlineAt:new Date(0)}});const expired=await f.service().closePosition(f.close());assert.equal(expired.close.state,'canceled');assert.equal(expired.close.active,false);assert.equal(f.writes.filter(w=>w[0]==='submit').length,1);assert.equal(f.writes.filter(w=>w[0]==='cancel').length,2);await f.service().closePosition(f.close());assert.equal(f.writes.filter(w=>w[0]==='cancel').length,2);});
  await t.test('protective acceptance with lost broker ID is discovered through durable client identity',async()=>{const f=await fixture();await f.stop();await Protection.updateOne({accountId:f.accountId},{$set:{brokerOrderId:null,state:'uncertain'}});const out=await f.service().closePosition(f.close());assert.equal(out.close.state,'acknowledged');assert.deepEqual(f.writes,[['cancel','stop-one'],['submit',4]]);});
  await t.test('production admission refuses unready execution before any intent or protective mutation',async()=>{const f=await fixture();const {executionReadiness}=require('../services/executionReadiness');executionReadiness.invalidate();const service=require('../services/orderLifecycleService').getOrderLifecycle({broker:f.broker,ownerId,expectedAccountId:f.accountId,strictRisk:false,loadSettings:async()=>({mode:'paper',dailyLimit:1000,weeklyLimit:1000,monthlyLimit:1000})});await assert.rejects(service.submit(f.buy('unready')),error=>error.code==='EXECUTION_NOT_READY');assert.equal(await Intent.countDocuments({accountId:f.accountId}),0);await f.stop();await assert.rejects(service.closePosition(f.close()),error=>error.code==='EXECUTION_NOT_READY');assert.equal(f.writes.length,0);assert.equal(await Close.countDocuments({accountId:f.accountId}),0);});
  await t.test('bounded recovery does no broker work while idle and restores stops after expired close',async()=>{const f=await fixture();const recovery=require('../services/positionCloseRecovery');let created=0;const deps={brokerFactory:()=>{created++;return f.broker;},lifecycleFactory:()=>f.service()};await recovery.recoverPositionCloses({ownerId,accountId:f.accountId},deps);assert.equal(created,0);await f.stop();const first=await f.service().closePosition(f.close());await Close.updateOne({_id:first.close._id},{$set:{deadlineAt:new Date(0)}});await recovery.recoverPositionCloses({ownerId,accountId:f.accountId},deps);assert.equal((await Close.findById(first.close._id)).active,false);assert.equal(f.writes.filter(w=>w[0]==='submit').length,2);assert.equal(created,1);assert.equal((await Protection.findOne({accountId:f.accountId})).state,'protected');});
  await t.test('protection restoration timeout stays scheduled and recovers accepted stop without duplication',async()=>{const f=await fixture();await f.stop();const first=await f.service().closePosition(f.close());await Close.updateOne({_id:first.close._id},{$set:{deadlineAt:new Date(0)}});const submit=f.broker.submitOrder;f.broker.submitOrder=async input=>{const result=await submit(input);if(input.orderType==='stop')throw new Error('stop acknowledgement lost');return result;};const recovery=require('../services/positionCloseRecovery');const deps={brokerFactory:()=>f.broker,lifecycleFactory:()=>f.service()};await recovery.recoverPositionCloses({ownerId,accountId:f.accountId},deps);assert.equal((await Close.findById(first.close._id)).needsProtectionRecovery,true);await recovery.recoverPositionCloses({ownerId,accountId:f.accountId},deps);assert.equal((await Protection.findOne({accountId:f.accountId})).state,'protected');assert.equal((await Close.findById(first.close._id)).needsProtectionRecovery,false);assert.equal(f.writes.filter(w=>w[0]==='submit').length,2);});
 } finally {await mongoose.connection.dropDatabase();await mongoose.disconnect();}
});
