'use strict';
const diagnostic=require('./startup-diagnostics.cjs'),probe=require('./crashpad-probe.cjs'),attestation=require('./sandbox-attestation.cjs');let startupStage='I';
diagnostic.record('browser',startupStage,'entered');
process.on('uncaughtExceptionMonitor',e=>diagnostic.failure('browser',startupStage,e));
const fs=require('fs'),net=require('net'),https=require('https'),crypto=require('crypto'),{chromium}=require('/opt/acceptance/node_modules/playwright');
startupStage='J';diagnostic.record('browser',startupStage,'attempt');
const c=require('./config.cjs').load(),{parseRequest,F,B}=require('./policy.cjs');const FRONT='https://'+F,BACK='https://'+B,assets=JSON.parse(fs.readFileSync('/config/assets.json'));
diagnostic.record('browser',startupStage,'complete');
const checks=['ownerConfiguration','authenticationConfiguration','databaseConnected','ownerIdentity','ownerSettings','persistence','paperMode','automationDisabled','schedulerSuppressed','paperDestination','paperBindingConfiguration','paperCredentialConfiguration'];
const save=(n,x)=>fs.writeFileSync('/evidence/'+n+'.json',JSON.stringify({run:c.run,at:new Date().toISOString(),...x},null,2));
const event=x=>fs.appendFileSync('/evidence/browser.jsonl',JSON.stringify({at:new Date().toISOString(),...x})+'\n');
function rpc(path,q){return new Promise((resolve,reject)=>{const s=net.createConnection(path);let b='';s.on('connect',()=>s.write(JSON.stringify(q)+'\n'));s.on('data',x=>b+=x);s.on('end',()=>{try{const r=JSON.parse(b);if(!r.ok)throw Error();resolve(r)}catch{reject(Error('PRIVATE_RPC_REJECTED'))}});s.on('error',reject);s.setTimeout(15000,()=>s.destroy(Error('PRIVATE_RPC_TIMEOUT')));});}
const gateway=phase=>rpc('/gateway/control.sock',{run:c.run,capability:c.capability,phase});
(async()=>{
const instance=crypto.randomUUID();let stage='PREFLIGHT',busy=false,pending=null,consumed=false,issued=null,sequence=0,beforeNonce=null,credentialCanary=null;const responses=[];
const executable='/opt/chromium/chrome-linux/chrome';
const version=require('node:child_process').spawnSync(executable,['--version'],{encoding:'utf8',timeout:5000,maxBuffer:4096});
const browserVersion=(version.stdout||'').match(/(?:Chromium|Google Chrome(?: for Testing)?) [0-9.]+/);
const browserIdentity={playwrightVersion:require('/opt/acceptance/node_modules/playwright/package.json').version,browserVersion:browserVersion?browserVersion[0]:'not emitted',versionProbeExit:version.status,executable,executableSha256:crypto.createHash('sha256').update(fs.readFileSync(executable)).digest('hex')};
diagnostic.record('browser','K','versions',browserIdentity);
startupStage='K';diagnostic.preflight();probe.metadata('before');startupStage='L';diagnostic.record('Chromium',startupStage,'attempt');
const context=await chromium.launchPersistentContext('/profile/chromium',{executablePath:'/opt/chromium/chrome-linux/chrome',headless:false,chromiumSandbox:true,serviceWorkers:'block',ignoreHTTPSErrors:false,acceptDownloads:false,viewport:{width:1280,height:900},ignoreDefaultArgs:['--unsafely-disable-devtools-self-xss-warnings','--enable-unsafe-swiftshader'],args:['--disable-breakpad','--disable-crash-reporter','--disable-quic','--host-resolver-rules=MAP day-trader-frontend.fly.dev 127.0.0.1, MAP day-trader-backend.fly.dev 127.0.0.1, MAP fonts.googleapis.com 127.0.0.1, MAP fonts.gstatic.com 127.0.0.1, MAP * ~NOTFOUND']});
startupStage='M';diagnostic.record('Chromium',startupStage,'complete');
const intercept=route=>{const r=route.request(),u=new URL(r.url()),h={...r.headers(),host:u.host};if(r.method()==='POST'&&!h['content-length'])h['content-length']=String(Buffer.byteLength(r.postData()||''));const d=u.protocol==='https:'&&!u.port&&!u.username&&!u.password&&parseRequest({method:r.method(),target:u.pathname+u.search,rawHeaders:Object.entries(h).flat()},assets);return d?route.continue():route.abort('blockedbyclient');};await context.route('**/*',intercept);
const page=context.pages()[0]||await context.newPage();page.setDefaultTimeout(20000);
context.on('response',r=>{const u=new URL(r.url());if(u.origin===BACK){responses.push({seq:++sequence,path:u.pathname,status:r.status(),method:r.request().method(),response:r});event({type:'response',seq:sequence,path:Object.hasOwn(require('./policy.cjs').routes,u.pathname)||['/api/login','/api/logout'].includes(u.pathname)?u.pathname:'other',status:r.status(),method:r.request().method()});}});
startupStage='N';await page.goto('chrome://sandbox');diagnostic.record('browser',startupStage,'complete');startupStage='O';await attestation.observeAndAssert(page,browserIdentity);save('sandbox',{pass:true,namespace:true,seccomp:true});diagnostic.record('browser',startupStage,'complete');
if(probe.enabled()){await probe.finish(context,page);probe.metadata('after');return;}
startupStage='P';diagnostic.record('browser',startupStage,'attempt');await page.goto(FRONT+'/login');await page.getByRole('button',{name:'Log In',exact:true}).waitFor();stage='AWAIT_CREDENTIAL';
function fail(){stage='FAILED';pending=null;credentialCanary=null;event({type:'failed'});}
async function fetchJSON(path){return page.evaluate(async url=>{const r=await fetch(url,{credentials:'include',cache:'no-store'});return {status:r.status,body:await r.json()}},BACK+path);}
async function readiness(label){const me=await fetchJSON('/api/me');if(me.status!==200||me.body.user?.id!==c.expectedOwner||me.body.user?.username!==c.username)throw Error('OWNER_MISMATCH');const r=await fetchJSON('/api/readiness'),b=r.body;const pass=r.status===200&&b.contractVersion===2&&b.profile==='owner-paper-maintenance'&&b.runtimeReady===true&&b.maintenanceReady===true&&checks.every(k=>b.checks?.[k]?.status==='pass')&&b.automation?.enabled===false&&b.automation?.isEnabled===false&&b.automation?.liveEnabled===false&&b.automation?.schedulerSuppressed===true&&b.automation?.activationAuthorized===false;
 save(label,{pass,status:r.status,contractVersion:b.contractVersion,profile:b.profile,runtimeReady:b.runtimeReady,maintenanceReady:b.maintenanceReady,requiredChecks:Object.fromEntries(checks.map(k=>[k,b.checks?.[k]?.status])),automation:b.automation,acceptance:b.acceptance,releaseReady:b.releaseReady,ownerExactMatch:true,instance,responseSequence:sequence});if(!pass)throw Error('READINESS_REJECTED');}
async function view(path,required){const start=sequence;await page.goto(FRONT+path);for(let i=0;i<120;i++){if(required.every(p=>responses.some(r=>r.seq>start&&r.path===p)))break;await page.waitForTimeout(100);}const actual={};for(const p of required){const rows=responses.filter(r=>r.seq>start&&r.path===p);if(rows.length!==1||rows[0].status!==200)throw Error('VIEW_RESPONSE_REJECTED');actual[p]=await rows[0].response.json();}await page.waitForTimeout(300);const text=await page.locator('body').innerText();if(text.includes('Could not load')||text.includes('Request failed'))throw Error('VIEW_RENDER_FAILED');for(const [route,data] of Object.entries(actual)){const key=route.endsWith('/decisions')?'decisions':route.endsWith('/robotrader/orders')?'orders':route.endsWith('/audit')||route.endsWith('/notifications')?'events':route.endsWith('/account')?'positions':null;const records=key?data[key]:Array.isArray(data)?data:null;if(records&&records.length===0)throw Error('EMPTY_REHEARSAL_VIEW');}const arrays=Object.values(actual).flatMap(x=>Array.isArray(x)?[x]:['decisions','orders','events','positions'].filter(k=>Array.isArray(x[k])).map(k=>x[k]));if(c.profile==='production-rehearsal'&&(!arrays.length||!arrays.some(a=>a.length>0)))throw Error('EMPTY_REHEARSAL_VIEW');const symbols=arrays.flatMap(a=>a.map(x=>x.symbol||x.subject).filter(Boolean));if(symbols.some(x=>!text.includes(x)))throw Error('DATA_NOT_RENDERED');return {path,requiredResponses:required.length,arrayCounts:arrays.map(a=>a.length),renderedRecordChecks:symbols.length,pass:true};}
const robo=['settings','decisions','orders','performance','audit','health','reconciliation-status'].map(p=>'/api/robotrader/'+p);
async function rawPrior(){return new Promise(resolve=>{const r=https.request({hostname:'127.0.0.1',port:443,servername:B,ca:fs.readFileSync('/tls/cert.pem'),path:'/api/me',headers:{host:B,cookie:issued.name+'='+issued.value},timeout:10000},s=>{s.resume();s.on('end',()=>resolve(s.statusCode));});r.on('error',()=>resolve(null));r.on('timeout',()=>r.destroy());r.end();});}
async function leakage(){let files=0,hits=0;for(const root of ['/evidence','/tools']){function walk(dir){for(const f of fs.readdirSync(dir,{withFileTypes:true})){const p=dir+'/'+f.name;if(f.isDirectory())walk(p);else if(f.isFile()){files++;const b=fs.readFileSync(p);if([credentialCanary,issued?.value,c.capability].some(s=>s&&b.includes(Buffer.from(s))))hits++;}}}walk(root);}save('leakage',{files,hits,pass:hits===0,knownPasswordCompared:!!credentialCanary,knownSessionCompared:!!issued});if(hits)throw Error('LEAKAGE');return {files,hits,pass:true};}
async function login(password){await gateway('AUTH');stage='AUTHENTICATE';credentialCanary=password;const response=page.waitForResponse(r=>r.url()===BACK+'/api/login'&&r.request().method()==='POST');await page.getByPlaceholder('Username',{exact:true}).fill(c.username);await page.getByPlaceholder('Password',{exact:true}).fill(password);password=null;await page.getByRole('button',{name:'Log In',exact:true}).click();const r=await response;if(r.status()!==200)throw Error('AUTH_FAILED');await page.getByRole('button',{name:'Sign Out',exact:true}).waitFor();issued=(await context.cookies(BACK)).find(x=>x.name==='daytrader_session');if(!issued?.httpOnly||!issued?.secure)throw Error('COOKIE_REJECTED');stage='OBSERVE_BEFORE_RESTART';save('login',{pass:true,status:200,cookieAccepted:true,httpOnly:true,secure:true,sameSite:issued.sameSite,instance});}
const commands={
 status:async()=>({stage,instance,busy,credentialConsumed:consumed,authenticated:!!issued}),
 'credential-request':async()=>{if(stage!=='AWAIT_CREDENTIAL'||pending||consumed)throw Error();pending={request:crypto.randomBytes(32).toString('hex'),expires:Date.now()+120000};return {...pending,destination:BACK,source:c.source,lock:c.lock,instance};},
 'credential-cancel':async q=>{if(!pending||pending.request!==q.request)throw Error();pending=null;stage='CANCELLED';return {cancelled:true};},
 'credential-consume':async q=>{if(stage!=='AWAIT_CREDENTIAL'||consumed||!pending||pending.request!==q.request||Date.now()>pending.expires||typeof q.password!=='string'||!q.password||Buffer.byteLength(q.password)>1024)throw Error();consumed=true;pending=null;const fd=fs.openSync('/profile/credential-consumed','wx',0o600);fs.writeFileSync(fd,'consumed');fs.closeSync(fd);const pw=q.password;delete q.password;await login(pw);return {consumed:true,stage};},
 'observe-before':async()=>{if(stage!=='OBSERVE_BEFORE_RESTART')throw Error();await gateway('BEFORE');await readiness('readiness-before');const views=[];views.push(await view('/robo',robo));views.push(await view('/portfolio',['/api/paper-trades/account','/api/paper-trades/equity']));views.push(await view('/activity',['/api/paper-trades/orders','/api/paper-trades/trades','/api/robotrader/notifications']));const staticResult=await page.evaluate(async()=>{const r=await fetch('/static/js/acceptance-missing.js',{cache:'no-store'});return {status:r.status,type:r.headers.get('content-type')}});if(staticResult.status!==404)throw Error();save('views-before',{views,staticResult,pass:true});await gateway('HOLD');stage='AWAIT_APPROVED_RESTART';beforeNonce=crypto.randomBytes(24).toString('hex');return {stage,restartRequest:beforeNonce,instance};},
 'restart-completed':async q=>{if(stage!=='AWAIT_APPROVED_RESTART'||q.request!==beforeNonce||!q.receipt||q.receipt.image!==c.backendImage||!q.receipt.before||!q.receipt.after||q.receipt.before===q.receipt.after||q.receipt.sameDatabase!==true||q.receipt.sameAuthConfiguration!==true)throw Error();beforeNonce=null;await gateway('AFTER');stage='OBSERVE_AFTER_RESTART';const cookie=(await context.cookies(BACK)).find(x=>x.name===issued.name);if(cookie?.value!==issued.value)throw Error();await readiness('readiness-after');const v=await view('/robo',robo);save('restart',{pass:true,sameSession:true,sameContext:true,instance,view:v,processReplacementVerifiedByOrchestrator:true});stage='LOGOUT';return {stage};},
 logout:async()=>{if(stage!=='LOGOUT')throw Error();await gateway('LOGOUT');stage='VERIFY_REVOCATION';const r=page.waitForResponse(r=>r.url()===BACK+'/api/logout'&&r.request().method()==='POST');await page.getByRole('button',{name:'Sign Out',exact:true}).click();const response=await r;if(response.status()!==200||(await response.json()).revoked!==true)throw Error();await response.finished();const priorStatus=await rawPrior(),current=await fetchJSON('/api/me'),cookieRemoved=!(await context.cookies(BACK)).some(x=>x.name===issued.name);if(priorStatus!==401||current.status!==401||!cookieRemoved)throw Error();save('logout',{pass:true,status:200,priorStatus,currentStatus:current.status,cookieRemoved,instance});await leakage();credentialCanary=null;await gateway('DONE');stage='CLEANUP';return {stage,pass:true};},
 'security-probe':async()=>{if(stage!=='AWAIT_CREDENTIAL')throw Error();const p=await context.newPage();await p.goto(BACK+'/health');let result;try{await context.unroute('**/*',intercept);result=await p.evaluate(async()=>{const a=await fetch('/api/recommendations?x=1'),b=await fetch('/api/me');return {denied:a.status,control:b.status}});}finally{await context.route('**/*',intercept)}await p.close();if(result.denied!==403||result.control!==401)throw Error();save('security-probe',{...result,pass:true,instance});return {pass:true};},
 leakage,
 shutdown:async()=>{pending=null;credentialCanary=null;issued=null;await context.close();setTimeout(()=>process.exit(0),50);return {closed:true};}
};
startupStage='Q';diagnostic.record('browser',startupStage,'attempt');
fs.mkdirSync('/control',{recursive:true,mode:0o700});const path='/control/controller.sock';if(fs.existsSync(path))fs.unlinkSync(path);
const server=net.createServer({allowHalfOpen:true},s=>{let b='',used=false;s.setTimeout(130000,()=>s.destroy());s.on('data',async x=>{if(used)return;b+=x;if(b.length>4096){used=true;return s.end('{"ok":false}');}if(!b.includes('\n'))return;used=true;let acquired=false;try{const q=JSON.parse(b);b='';const allowed=['run','capability','command',...(q.command==='credential-consume'?['request','password']:q.command==='credential-cancel'?['request']:q.command==='restart-completed'?['request','receipt']:[])];if(Object.keys(q).some(k=>!allowed.includes(k))||q.run!==c.run||q.capability!==c.capability||!Object.hasOwn(commands,q.command)||busy)throw Error();busy=true;acquired=true;const result=await commands[q.command](q);s.end(JSON.stringify({ok:true,...result}));}catch(e){event({type:'check-rejected',code:/^[A-Z_]+$/.test(e.message)?e.message:'CHECK_FAILED'});if(acquired&&!['AWAIT_CREDENTIAL','AWAIT_APPROVED_RESTART'].includes(stage))fail();s.end('{"ok":false,"error":"CONTROL_REJECTED_OR_CHECK_FAILED"}');}finally{if(acquired)busy=false;}});});server.on('error',e=>diagnostic.failure('controller-socket','Q',e));server.listen(path,()=>{fs.chmodSync(path,0o600);diagnostic.record('controller-socket','Q','ready',{socket:diagnostic.metadata(path)});});save('controller-ready',{stage,instance,pass:true});
process.on('SIGTERM',async()=>{pending=null;credentialCanary=null;await context.close();process.exit(0)});
})().catch(e=>{diagnostic.failure('Chromium/browser',startupStage,e);probe.metadata('after');const message=String(e.message);const code=/sandbox/i.test(message)?'SANDBOX_START_FAILED':/EACCES|permission/i.test(message)?'PERMISSION_START_FAILED':/executable.*exist/i.test(message)?'BROWSER_EXECUTABLE_MISSING':'START_FAILED';save('controller-start',{pass:false,error:code});process.exit(1)});
