'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm'),{EventEmitter}=require('events'),{spawnSync}=require('child_process');
const modulePath=path.resolve(__dirname,'../tools/browser-finalization.cjs'),source=fs.readFileSync(path.resolve(__dirname,'../tools/browser.cjs'),'utf8'),secret='password capability session cookie JWT /private/path';
const id='00000000-0000-4000-8000-000000000001';
function fixture(failAt){const rows=[],proc=new EventEmitter(),calls=[],timers=[];const observer=require(modulePath).observe({instance:id,process:proc,write:r=>rows.push(r)});const op=name=>{calls.push(name);if(name===failAt)throw Error(secret)};const scope={shutdownDiagnostic:observer,entry:{invalidate:()=>op('invalidate')},fs:{rmSync:()=>op('remove')},preauthPath:secret,routeFacts:()=>op('route'),pending:secret,credentialCanary:secret,issued:secret,context:{close:async()=>op('close')},probe:{metadata:()=>op('metadata')},setTimeout:(fn,ms)=>{timers.push({fn,ms});op('timer')},process:{exit:c=>{calls.push('exit');proc.emit('exit',c)}}};
 const body=source.match(/shutdown:async\(\)=>\{([\s\S]*?)\n\};/)[1];const shutdown=vm.runInNewContext('(async()=>{'+body+')',scope);return {rows,proc,calls,timers,observer,scope,shutdown};}
test('actual shutdown preserves operations and 50ms timer, with full stage observations',async()=>{const f=fixture();assert.equal((await f.shutdown()).closed,true);assert.deepEqual(f.calls,['invalidate','remove','route','close','metadata','timer']);assert.equal(f.timers.length,1);assert.equal(f.timers[0].ms,50);assert.equal(f.scope.pending,null);assert.equal(f.scope.issued,null);assert.deepEqual(f.rows.map(r=>r.stage),['BS01_SHUTDOWN_ENTER','BS02_ENTRY_INVALIDATED','BS03_PREAUTH_REMOVE_COMPLETE','BS04_ROUTE_FACTS_COMPLETE','BS05_PRIVATE_STATE_CLEARED','BS06_CONTEXT_CLOSE_START','BS07_CONTEXT_CLOSE_FINISH','BS08_CRASH_METADATA_START','BS09_CRASH_METADATA_FINISH','BS10_EXIT_TIMER_ARMED','BS11_COMMAND_RETURN']);assert.ok(!JSON.stringify(f.rows).includes(secret));});
for(const [op,category] of [['invalidate','ENTRY_INVALIDATION_FAILED'],['remove','PREAUTH_REMOVE_FAILED'],['route','ROUTE_FACTS_FAILED'],['close','CONTEXT_CLOSE_FAILED'],['metadata','CRASH_METADATA_FAILED']])test('actual shutdown retains and rethrows '+op+' failure',async()=>{const f=fixture(op);await assert.rejects(f.shutdown(),e=>e.message===secret);assert.equal(f.rows.at(-1).failure,category);assert.equal(f.timers.length,0);assert.ok(!JSON.stringify(f.rows).includes(secret));});
for(const flush of [true,false])test('process exit distinguishes response flush '+flush+' without awaiting it',async()=>{const f=fixture(),s=new EventEmitter();f.observer.watch(s);await f.shutdown();f.observer.mark('CS01_COMMAND_RESOLVED');f.observer.mark('CS02_RESPONSE_END_CALLED');if(flush)s.emit('finish');f.timers[0].fn();const last=f.rows.at(-1);assert.equal(last.stage,'browser-process-exit');assert.equal(last.exitCode,0);assert.equal(last.responseFlushed,flush);for(const k of ['exitTimerArmed','commandReturned','responseEndCalled','contextClosed','crashMetadataCompleted'])assert.equal(last[k],true);assert.equal(s.listenerCount('error'),0);});
test('real child exits normally with synchronous observer and failed writes cannot prevent it',()=>{for(const fail of [false,true]){const script=`require(${JSON.stringify(modulePath)}).observe({instance:${JSON.stringify(id)},write:r=>{${fail?"throw Error('private')":"process.stdout.write(JSON.stringify(r)+'\\n')"}}});process.exit(7);`;const child=spawnSync(process.execPath,['-e',script],{encoding:'utf8',timeout:3000});assert.equal(child.status,7);if(!fail)assert.equal(JSON.parse(child.stdout).exitCode,7);}});
test('observer rejects arbitrary fields and bounds receipts',()=>{const rows=[],proc=new EventEmitter(),d=require(modulePath).observe({instance:id,process:proc,write:r=>rows.push(r)});for(let i=0;i<400;i++)d.mark('BS01_SHUTDOWN_ENTER',{secret});assert.ok(rows.length<=257);assert.ok(!JSON.stringify(rows).includes(secret));});

test('actual controller server observes resolved/end/finish without gating its response',async()=>{
 const f=fixture(),socket=new EventEmitter();let connection,payload;
 socket.setTimeout=()=>{};socket.end=data=>{payload=data;socket.emit('finish');};
 const server={on(){return this},listen(_,cb){cb()}};
 const net={createServer:(_,fn)=>{connection=fn;return server}};
 const body=source.slice(source.indexOf('const server=net.createServer({allowHalfOpen:true}'),source.indexOf("process.on('SIGTERM'"));
 const scope={net,instance:id,shutdownDiagnostic:f.observer,c:{run:'r',capability:'c'},commands:{shutdown:async()=>({closed:true})},busy:false,path:'unused',fs:{chmodSync(){}},diagnostic:{record(){},metadata(){return {}},failure(){}},save(){},stage:'CLEANUP',event(){assert.fail('unexpected rejection')},fail(){assert.fail('unexpected failure')}};
 vm.runInNewContext(body,scope);connection(socket);socket.emit('data',JSON.stringify({run:'r',capability:'c',command:'shutdown'})+'\n');await new Promise(r=>setImmediate(r));
 assert.deepEqual(JSON.parse(payload),{ok:true,closed:true});assert.deepEqual(f.rows.map(r=>r.stage),['CS01_COMMAND_RESOLVED','CS02_RESPONSE_END_CALLED','CS03_RESPONSE_FINISH_OR_CALLBACK']);assert.equal(scope.busy,false);
});
