'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {securityProbe,fetchPair,observeBoundary}=require('../tools/security-probe.cjs');
const poison='https://secret.invalid/private cookie=generated-secret /Users/private/token';
function fixture(failure,denied=403,control=401,recordFailure=0){
 const receipts=[],calls=[],invalidate=[];const error=Object.assign(Error(poison),{name:'UntrustedName',code:poison});
 const op=async(name,value)=>{calls.push(name);if(failure?.includes(name))throw error;return value;};
 const page={on:()=>{},off:()=>{},url:()=> 'https://day-trader-backend.fly.dev/health',goto:()=>op('navigation',{status:()=>200}),close:()=>op('close'),evaluate:async fn=>{calls.push('evaluate');const old=global.fetch;global.fetch=async path=>op(path.includes('recommendations')?'denied':'control',{status:path.includes('recommendations')?denied:control});try{return await fn();}finally{global.fetch=old;}}};
 const context={newPage:()=>op('create',page),unroute:()=>op('unroute'),route:()=>op('restore')};
 return {receipts,calls,invalidate,run:()=>securityProbe({context,intercept:()=>{},currentStage:()=> 'AWAIT_CREDENTIAL',invalidate:()=>invalidate.push(true),record:r=>{if(recordFailure&&r.stages[recordFailure-1].started&&!r.stages[recordFailure-1].completed)throw error;receipts.push(structuredClone(r));}}),last:()=>receipts.at(-1)};
}
const row=(f,n)=>f.last().stages[n-1];
test('successful fixture preserves all operations and ten stage receipts',async()=>{const f=fixture();await f.run();assert.deepEqual(f.calls,['create','navigation','unroute','evaluate','denied','control','restore','close']);assert.equal(f.last().pass,true);assert.equal(f.last().stages.length,10);assert.ok(f.last().stages.every(x=>x.started&&x.completed&&x.success));assert.equal(row(f,3).httpStatus,200);assert.equal(row(f,3).expectedOriginReached,true);assert.equal(row(f,5).httpStatus,403);assert.equal(row(f,6).httpStatus,401);});
for(const [failure,stage] of [['navigation',3],['unroute',4],['denied',5],['control',6],['restore',7],['close',8]])test(failure+' failure retains exact stage and independent cleanup',async()=>{const f=fixture([failure]);await assert.rejects(f.run());assert.equal(row(f,stage).success,false);assert.equal(f.last().firstFailure,row(f,stage).stage);assert.ok(f.calls.includes('close'));assert.equal(f.calls.includes('restore'),failure!=='navigation');if(['navigation','unroute'].includes(failure))assert.ok(!f.calls.includes('denied'));if(failure==='denied')assert.ok(!f.calls.includes('control'));if(failure==='restore')assert.equal(f.invalidate.length,1);assert.ok(!JSON.stringify(f.receipts).includes(poison));assert.ok(!JSON.stringify(f.receipts).includes('UntrustedName'));});
test('both inner and restoration failures survive and restoration invalidates state',async()=>{const f=fixture(['denied','restore']);await assert.rejects(f.run());assert.equal(row(f,5).success,false);assert.equal(row(f,7).success,false);assert.equal(f.last().restorationFatal,true);assert.equal(f.invalidate.length,1);assert.ok(f.calls.includes('close'));});
for(const [denied,control,stage] of [[400,401,9],[403,403,10]])test('actual statuses retained before assertion '+stage,async()=>{const f=fixture([],denied,control);await assert.rejects(f.run());assert.equal(row(f,stage).success,false);assert.equal(row(f,9).actualStatus,denied);assert.equal(row(f,9).expectedStatus,403);assert.equal(row(f,10).actualStatus,control);assert.equal(row(f,10).expectedStatus,401);assert.equal(f.calls.at(-1),'close');});
test('stage check and page create failure do not alter main page or fabricate cleanup',async()=>{const f=fixture(['create']);await assert.rejects(f.run());assert.equal(row(f,2).success,false);assert.equal(row(f,8).started,false);assert.equal(f.calls.includes('unroute'),false);});
test('fetch receipt uses exact original relative paths and never includes body/url/error text',async()=>{const paths=[],old=global.fetch;global.fetch=async p=>{paths.push(p);return {status:paths.length===1?403:401,body:poison,url:poison,headers:{cookie:poison}}};try{const r=await fetchPair();assert.deepEqual(paths,['/api/recommendations?x=1','/api/me']);assert.equal(r.stages.length,2);assert.ok(!JSON.stringify(r).includes(poison));}finally{global.fetch=old;}});
test('boundary receipts use fixed path IDs, handler counts and exact status only',()=>{const {EventEmitter}=require('node:events'),rows=[],res=new EventEmitter();res.statusCode=403;observeBoundary({method:'GET',url:'/api/recommendations?x=1',headers:{host:'day-trader-backend.fly.dev',cookie:poison}},res,'tls',r=>rows.push(r));res.emit('finish');assert.deepEqual(rows,[{boundary:'tls',pathId:'denied-recommendations-query',event:'handler',method:'GET'},{boundary:'tls',pathId:'denied-recommendations-query',event:'response',method:'GET',httpStatus:403}]);observeBoundary({method:'GET',url:poison,headers:{}},res,'tls',r=>rows.push(r));assert.equal(rows.length,2);});
test('wrong controller stage fails before creating any page',async()=>{let created=false;const receipts=[];await assert.rejects(securityProbe({context:{newPage:async()=>{created=true}},intercept:()=>{},currentStage:()=> 'FAILED',invalidate:()=>{},record:r=>receipts.push(structuredClone(r))}));assert.equal(created,false);assert.equal(receipts.at(-1).firstFailure,'SP01_STAGE_CHECK');});
test('safe error categories expose no exception text, URLs, paths or arbitrary code',()=>{const {safeError}=require('../tools/security-probe.cjs');for(const message of [poison,'net::ERR_CERT_AUTHORITY_INVALID '+poison,'Refused because Content Security Policy '+poison,'Failed to fetch '+poison]){const r=safeError({name:'TypeError',message,stack:poison,code:poison});assert.deepEqual(Object.keys(r),['errorClass','safeErrorCode']);assert.ok(!JSON.stringify(r).includes(poison));assert.ok(!JSON.stringify(r).includes('secret.invalid'));}});

for(const stage of [7,8])test('evidence write failure cannot prevent cleanup stage '+stage,async()=>{const f=fixture([],403,401,stage);await assert.rejects(f.run());assert.ok(f.calls.includes('restore'));assert.ok(f.calls.includes('close'));assert.equal(f.last().pass,false);assert.equal(f.last().evidenceWriteFailed,true);});
