'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{EventEmitter,errorMonitor}=require('events'),fs=require('fs'),os=require('os'),path=require('path'),{spawnSync}=require('child_process');
const poison='private.invalid 192.0.2.77 /private/secret credential certificate cookie raw-stack';
const modulePath=path.resolve(__dirname,'../tools/standin-lifecycle.cjs');
function fixture(write){const rows=[],proc=new EventEmitter(),https=new EventEmitter(),canary=new EventEmitter();const observer=require(modulePath).observe({process:proc,write:write||((r)=>rows.push(r))});observer.https(https);observer.canary(canary);return {rows,proc,https,canary};}
test('process and listener receipts share monotonic order and retain listened flags',()=>{const f=fixture();f.https.emit('listening');f.canary.emit('listening');f.proc.emit('beforeExit',0);f.proc.emit('exit',0);assert.deepEqual(f.rows.map(r=>r.stage),['STP01_PROCESS_STARTED','STP02_HTTPS_LISTENING','STP03_CANARY_LISTENING','CAN01_SERVER_LISTENING','STP05_PROCESS_BEFORE_EXIT','STP06_PROCESS_EXIT']);assert.deepEqual(f.rows.map(r=>r.order),[1,2,3,4,5,6]);assert.equal(f.rows.at(-1).exitCode,0);assert.equal(f.rows.at(-1).httpsListened,true);assert.equal(f.rows.at(-1).canaryListened,true);});
for(const code of ['EPIPE','ECONNRESET',poison])for(const origin of ['uncaughtException','unhandledRejection',poison])test('fatal allowlist '+(code===poison?'unclassified':code)+' '+(origin===poison?'other':origin),()=>{const f=fixture();f.proc.emit('uncaughtExceptionMonitor',Object.assign(Error(poison),{code,stack:poison}),origin);const r=f.rows.at(-1);assert.equal(r.stage,'STP04_FATAL_EXCEPTION_MONITOR');assert.equal(r.safeErrorCode,code===poison?'UNCLASSIFIED_STANDIN_FATAL':code);assert.equal(r.origin,origin===poison?'other':origin);assert.equal(f.proc.listenerCount('uncaughtException'),0);assert.equal(f.proc.listenerCount('unhandledRejection'),0);assert.ok(!JSON.stringify(f.rows).includes(poison));});
test('canary accepted/error/close observations do not handle errors and correlate fatal identity',()=>{const f=fixture(),s=new EventEmitter();f.canary.emit('connection',s);const error=Object.assign(Error(poison),{code:'EPIPE'});assert.equal(s.listenerCount('error'),0);assert.equal(s.listenerCount(errorMonitor),1);assert.throws(()=>s.emit('error',error),e=>e===error);f.proc.emit('uncaughtExceptionMonitor',error,'uncaughtException');s.emit('close',true);assert.deepEqual(f.rows.slice(1).map(r=>r.stage),['CAN02_CONNECTION_ACCEPTED','CAN03_SOCKET_ERROR_MONITOR','STP04_FATAL_EXCEPTION_MONITOR','CAN04_SOCKET_CLOSE']);assert.equal(f.rows[3].source,'canary-socket');assert.equal(f.rows[3].connectionId,1);assert.equal(f.rows.at(-1).hadError,true);});
for(const type of ['canary','https'])test(type+' server error remains unhandled',()=>{const f=fixture(),error=Object.assign(Error(poison),{code:'ERR_SOCKET_CLOSED'});assert.throws(()=>f[type].emit('error',error),e=>e===error);assert.equal(f.rows.at(-1).stage,type==='canary'?'CAN05_SERVER_ERROR_MONITOR':'HTTPS01_SERVER_ERROR_MONITOR');assert.equal(f.rows.at(-1).safeErrorCode,'ERR_SOCKET_CLOSED');assert.equal(f[type].listenerCount('error'),0);});
test('HTTPS accepted raw and secure socket error monitors preserve ordinary handlers',()=>{const f=fixture();for(const event of ['connection','secureConnection']){const s=new EventEmitter();f.https.emit(event,s);const e=Object.assign(Error(poison),{code:'ECONNRESET'});assert.equal(s.listenerCount('error'),0);assert.throws(()=>s.emit('error',e),x=>x===e);assert.equal(f.rows.at(-1).stage,'HTTPS02_SOCKET_ERROR_MONITOR');}assert.equal(f.https.listenerCount('tlsClientError'),0);});
test('bounded evidence has overflow marker; failed writing and hostile error getters never affect behavior',()=>{const f=fixture();for(let i=0;i<400;i++)f.canary.emit('connection',new EventEmitter());assert.equal(f.rows.length,257);assert.equal(f.rows.at(-1).stage,'STP_OBSERVATION_OVERFLOW');const bad=fixture(()=>{throw Error(poison)}),s=new EventEmitter();assert.doesNotThrow(()=>bad.canary.emit('connection',s));const e=Object.assign(Error(poison),{code:'EPIPE'});assert.throws(()=>s.emit('error',e),x=>x===e);assert.doesNotThrow(()=>bad.proc.emit('exit',1));assert.doesNotThrow(()=>bad.proc.emit('uncaughtExceptionMonitor',{get code(){throw Error(poison)}},'uncaughtException'));});
for(const mode of ['throw','socket','rejection','write-failure'])test('isolated child remains fatal with monitor: '+mode,()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'standin-monitor-test-')),file=path.join(dir,'receipts.jsonl');
 try{const script=`const fs=require('fs'),{EventEmitter}=require('events');const o=require(${JSON.stringify(modulePath)}).observe({write:r=>{${mode==='write-failure'?"throw Error('synthetic-write-failure');":`fs.appendFileSync(${JSON.stringify(file)},JSON.stringify(r)+'\\n');`}}});if(process.listenerCount('uncaughtException')||process.listenerCount('unhandledRejection'))process.exit(97);const e=Object.assign(Error(${JSON.stringify(poison)}),{code:'EPIPE'});${mode==='rejection'?'Promise.reject(e)':mode==='socket'?"const server=new EventEmitter(),socket=new EventEmitter();o.canary(server);server.emit('connection',socket);socket.emit('error',e)":'throw e'};`;
 const child=spawnSync(process.execPath,['-e',script],{encoding:'utf8',timeout:5000});assert.equal(child.error,undefined);assert.equal(child.status,1);assert.equal(child.signal,null);
 if(mode!=='write-failure'){const content=fs.readFileSync(file,'utf8'),rows=content.trim().split('\n').map(JSON.parse);assert.ok(!content.includes(poison));const fatal=rows.find(r=>r.stage==='STP04_FATAL_EXCEPTION_MONITOR');assert.equal(fatal.safeErrorCode,'EPIPE');assert.equal(fatal.origin,mode==='rejection'?'unhandledRejection':'uncaughtException');assert.equal(rows.at(-1).stage,'STP06_PROCESS_EXIT');assert.equal(rows.at(-1).exitCode,1);if(mode==='socket')assert.equal(fatal.source,'canary-socket');}
 }finally{fs.rmSync(dir,{recursive:true,force:true});}
});
test('observer write failure does not turn normal child exit fatal',()=>{const child=spawnSync(process.execPath,['-e',`require(${JSON.stringify(modulePath)}).observe({write:()=>{throw Error('synthetic')}})`],{encoding:'utf8',timeout:5000});assert.equal(child.status,0);});
test('real stand-in retains canary payload, callback order, ports and bind addresses',()=>{const vm=require('vm'),rows=[],servers=[],proc=new EventEmitter();const make=(type,fn)=>{const server=new EventEmitter();server.on(type==='canary'?'connection':'request',fn);server.listen=(port,address)=>{server.bind=[port,address];server.emit('listening');};servers.push(server);return server;};const deps={https:{createServer:(_,fn)=>make('https',fn)},net:{createServer:fn=>make('canary',fn)},fs:{readFileSync:()=>'',appendFileSync(){}},http:{},'./standin-lifecycle.cjs':{observe:()=>require(modulePath).observe({process:proc,write:r=>rows.push(r)})},'./transport-observation.cjs':{observeStandin:()=>({http(){}})}};vm.runInNewContext(fs.readFileSync(path.resolve(__dirname,'../tools/standin.cjs'),'utf8'),{require:n=>deps[n]});assert.deepEqual(servers.map(s=>s.bind),[[443,'0.0.0.0'],[80,'0.0.0.0']]);const socket=new EventEmitter(),payloads=[];socket.end=data=>{assert.equal(rows.some(r=>r.stage==='CAN02_CONNECTION_ACCEPTED'),false);payloads.push(data)};servers[1].emit('connection',socket);assert.deepEqual(payloads,['synthetic-canary']);assert.equal(socket.listenerCount('error'),0);assert.ok(rows.some(r=>r.stage==='CAN02_CONNECTION_ACCEPTED'));});
