'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),{EventEmitter,errorMonitor}=require('events');
const O=require('../tools/transport-observation.cjs');
const poison='private.invalid 192.0.2.77 certificate cookie credential body stack';
function fixture(){
 const rows=[],t=O.gatewayTrace(17,{host:'day-trader-backend.fly.dev',path:'/health',method:'GET'},x=>rows.push(x));
 const socket=new EventEmitter();Object.assign(socket,{authorized:true,setTimeout(n,fn){this.timeout=n;this.timer=fn;},destroy(e){this.destroyed=true;if(e)this.emit('error',e);}});
 const request=new EventEmitter();Object.assign(request,{end(body){this.body=body;},destroy(e){this.emit('error',e);}});
 const effects={created:0,requests:0,destroyedAgent:0};let response;
 const tls={checkServerIdentity(){},connect(options){effects.created++;effects.tls=options;return socket;}};
 const https={Agent:class{constructor(options){effects.agent=options;}destroy(){effects.destroyedAgent++;}},request(options,cb){effects.requests++;effects.http=options;response=cb;return request;}};
 const module={exports:{}};vm.runInNewContext(fs.readFileSync(require.resolve('../tools/transport.cjs'),'utf8'),{require:n=>n==='tls'?tls:n==='https'?https:n==='fs'?fs:n==='./transport-observation.cjs'?O:require(n),module,Buffer});
 const c={upstreams:{'day-trader-backend.fly.dev':['192.0.2.77']}};
 return {rows,t,socket,request,effects,c,...module.exports,response:r=>response(r),stages:()=>rows.map(x=>x.stage)};
}
const has=(f,stage)=>f.rows.find(x=>x.stage===stage);
test('destination rejection records before any socket creation and preserves rejection',async()=>{const f=fixture();await assert.rejects(f.connect({upstreams:{}},'private.invalid',f.t),/DESTINATION_REJECTED/);assert.equal(f.effects.created,0);assert.equal(has(f,'GT01_DESTINATION_LOOKUP').success,false);});
for(const [code,tcp] of [['ECONNREFUSED',false],['ERR_SSL_WRONG_VERSION_NUMBER',true]])test('socket error preserves exact rejection and TCP boundary '+code,async()=>{const f=fixture(),p=f.connect(f.c,'day-trader-backend.fly.dev',f.t);if(tcp)f.socket.emit('connect');const e=Object.assign(Error(poison),{code});f.socket.emit('error',e);await assert.rejects(p,x=>x===e);assert.equal(!!has(f,'GT03_TCP_CONNECT'),tcp);assert.equal(has(f,'GT10_TLS_SOCKET_ERROR').safeErrorCode,code==='ECONNREFUSED'?code:'TLS_PROTOCOL_ERROR');assert.equal(!!has(f,'GT04_SECURE_CONNECT'),false);});
test('unauthorized secureConnect retains authorization failure and original destroy',async()=>{const f=fixture(),p=f.connect(f.c,'day-trader-backend.fly.dev',f.t);f.socket.authorized=false;f.socket.authorizationError='CERT_HAS_EXPIRED';f.socket.emit('secureConnect');await assert.rejects(p,/TLS_REJECTED/);assert.equal(f.socket.destroyed,true);assert.equal(has(f,'GT05_TLS_AUTHORIZATION').safeErrorCode,'TLS_CERT_EXPIRED');assert.equal(has(f,'GT05_TLS_AUTHORIZATION').authorized,false);});
async function connected(){const f=fixture(),body=Buffer.from('abc');const p=f.forward(f.c,{host:'day-trader-backend.fly.dev',target:'/health',method:'GET',headers:{}},body,r=>{f.received=r},f.t);f.socket.emit('connect');f.socket.emit('secureConnect');assert.equal(await p,f.request);f.body=body;return f;}
test('authorized TLS then request error records before headers; original body zeroing preserved',async()=>{const f=await connected();f.request.emit('error',Object.assign(Error(poison),{code:'ECONNRESET'}));assert.equal(has(f,'GT05_TLS_AUTHORIZATION').authorized,true);assert.equal(has(f,'GT09_HTTP_REQUEST_ERROR').safeErrorCode,'ECONNRESET');assert.equal(!!has(f,'GT08_RESPONSE_HEADERS'),false);assert.deepEqual(f.body,Buffer.alloc(3));});
test('successful response, finish, close preserve socket Agent and timeout semantics',async()=>{const f=await connected(),r={statusCode:200,headers:{cookie:poison},body:poison};f.request.emit('finish');f.response(r);f.request.emit('close');assert.equal(f.received,r);assert.equal(has(f,'GT08_RESPONSE_HEADERS').httpStatus,200);assert.ok(has(f,'GT07_HTTP_REQUEST_FINISH'));assert.ok(has(f,'GT13_HTTP_REQUEST_CLOSE'));assert.equal(f.effects.http.agent.createConnection(),f.socket);assert.equal(f.effects.agent.keepAlive,false);assert.equal(f.effects.http.timeout,10000);assert.equal(f.socket.timeout,8000);assert.equal(f.effects.tls.rejectUnauthorized,true);assert.equal(f.effects.destroyedAgent,1);});
test('upstream request timeout preserves original error and destroy',async()=>{const f=await connected();let original;f.request.on('error',e=>original=e.message);f.request.emit('timeout');assert.equal(original,'UPSTREAM_TIMEOUT');assert.equal(has(f,'GT11_TIMEOUT').component,'request');});
test('TLS timeout preserves original rejection',async()=>{const f=fixture(),p=f.connect(f.c,'day-trader-backend.fly.dev',f.t);f.socket.timer();await assert.rejects(p,/TLS_TIMEOUT/);assert.equal(has(f,'GT11_TIMEOUT').component,'socket');});
for(const secure of [false,true])test('close '+(secure?'after':'before')+' secure retains ordering without settling/destroying pending socket',async()=>{const f=fixture(),p=f.connect(f.c,'day-trader-backend.fly.dev',f.t);if(secure){f.socket.emit('secureConnect');await p;}f.socket.emit('close',true);assert.equal(has(f,'GT12_SOCKET_CLOSE').safeErrorCode,secure?'SOCKET_CLOSED_AFTER_SECURE':'SOCKET_CLOSED_BEFORE_SECURE');assert.equal(f.socket.destroyed,undefined);if(!secure){f.socket.emit('error',Error('cleanup'));await assert.rejects(p);}});
test('errorMonitor observes without handling formerly unhandled errors',async()=>{const f=fixture(),p=f.connect(f.c,'day-trader-backend.fly.dev',f.t);assert.equal(f.socket.listenerCount('error'),1);f.socket.emit('secureConnect');await p;assert.equal(f.socket.listenerCount('error'),0);assert.equal(f.socket.listenerCount(errorMonitor),1);const error=Error(poison);assert.throws(()=>f.socket.emit('error',error),x=>x===error);assert.ok(has(f,'GT10_TLS_SOCKET_ERROR'));});
test('stand-in connects raw TCP to TLS and HTTP with safe local IDs; no regular error listener',()=>{const rows=[],server=new EventEmitter(),obs=O.observeStandin(server,x=>rows.push(x));const raw=new EventEmitter(),tls=new EventEmitter();Object.assign(raw,{remoteAddress:'192.0.2.77',remotePort:56789,localPort:443});Object.assign(tls,{_parent:raw,servername:'day-trader-backend.fly.dev'});server.emit('listening');server.emit('connection',raw);server.emit('secureConnection',tls);const res=new EventEmitter();res.statusCode=200;obs.http({socket:tls,headers:{host:'day-trader-backend.fly.dev',cookie:poison}},res);res.emit('finish');raw.emit('close',false);assert.deepEqual(rows.map(x=>x.stage),['SI00_LISTENING','SI01_TCP_CONNECTION','SI02_TLS_SECURE_CONNECTION','SI04_HTTP_HANDLER_ENTER','SI05_HTTP_RESPONSE_FINISH','SI06_SOCKET_CLOSE']);assert.equal(new Set(rows.slice(1).map(x=>x.connectionId)).size,1);assert.equal(raw.listenerCount('error'),0);assert.equal(tls.listenerCount('error'),0);assert.ok(!JSON.stringify(rows).includes(poison));assert.ok(!JSON.stringify(rows).includes('192.0.2.77'));});
test('stand-in TLS client error before secure connection preserves server handling',()=>{const rows=[],server=new EventEmitter(),handled=[];server.on('tlsClientError',e=>handled.push(e));O.observeStandin(server,x=>rows.push(x));const raw=new EventEmitter(),tls={_parent:raw,servername:poison};server.emit('connection',raw);const error=Object.assign(Error(poison),{code:'ERR_SSL_WRONG_VERSION_NUMBER'});server.emit('tlsClientError',error,tls);assert.equal(handled[0],error);const r=rows.at(-1);assert.equal(r.stage,'SI03_TLS_CLIENT_ERROR');assert.equal(r.tcpObserved,true);assert.equal(r.secureObserved,false);assert.equal(r.hostClass,'unknown');assert.equal(r.safeErrorCode,'TLS_PROTOCOL_ERROR');});
test('safe errors map allowlist only; neither arbitrary metadata nor evidence failures change propagation',()=>{for(const code of ['ECONNRESET','ERR_TLS_CERT_ALTNAME_INVALID','CERT_HAS_EXPIRED','UNABLE_TO_VERIFY_LEAF_SIGNATURE',poison]){const row=O.safeError(Object.assign(Error(poison),{code,stack:poison}));assert.ok(!JSON.stringify(row).includes(poison));}const trace=O.gatewayTrace(1,{host:'day-trader-backend.fly.dev',path:'/health',method:'GET'},()=>{throw Error(poison)});assert.doesNotThrow(()=>trace.event('GT01_DESTINATION_LOOKUP',{success:true,headers:poison}));});
test('gateway branch names retain one local transport ID and reject arbitrary metadata',()=>{const f=fixture();for(const branch of ['GATEWAY_FORWARD_THROW','GATEWAY_UPSTREAM_REQUEST_ERROR','GATEWAY_REDIRECT_DENIED','GATEWAY_TRANSPORT_BODY_REJECTED'])f.t.branch(branch,Object.assign(Error(poison),{code:'ECONNRESET'}));assert.equal(f.rows.length,4);assert.ok(f.rows.every(x=>x.requestId===17));assert.ok(!JSON.stringify(f.rows).includes(poison));});
for(const mode of ['throw','request-error','redirect','body'])test('real gateway selects exact 502 branch '+mode,async()=>{
 const rows=[],r=new EventEmitter();let handler,journal;const server={on(){},listen(){}};
 const fakeFs={existsSync:()=>false,readFileSync:()=> '{}',writeFileSync:(_,s)=>{journal=JSON.parse(s)},renameSync(){},appendFileSync(){}};
 const observations={gatewayTrace:(id,d)=>O.gatewayTrace(id,d,x=>rows.push(x))};
 const moduleMap={'fs':fakeFs,'http':{createServer:(_,fn)=>(handler=fn,server)},'net':{createServer:()=>server},'./config.cjs':{load:()=>({run:'synthetic',lock:'lock',paperAlready:6,paperMaximum:60})},'./policy.cjs':{parseRequest:()=>({id:'health',host:'day-trader-backend.fly.dev',path:'/health',target:'/health',method:'GET',headers:mode==='body'?{'content-length':'2'}:{}}),requestCost:()=>0,limitFor:()=>10},'./security-probe.cjs':{observeBoundary(){}},'./transport-observation.cjs':observations,'./transport.cjs':{forward:async(c,d,b,cb,t)=>{assert.equal(typeof t.event,'function');if(mode==='throw')throw Object.assign(Error(poison),{code:'ECONNREFUSED'});if(mode==='redirect')cb({statusCode:302,resume(){}});return r;}}};
 vm.runInNewContext(fs.readFileSync(require.resolve('../tools/gateway.cjs'),'utf8'),{require:n=>moduleMap[n],Buffer,JSON,Date});
 const req={headers:{},rawHeaders:[],method:'GET',url:'/health',async *[Symbol.asyncIterator](){}};const res={headersSent:false,writeHead(s){this.status=s;this.headersSent=true;},end(){this.ended=true;}};
 await handler(req,res);if(mode==='request-error')r.emit('error',Object.assign(Error(poison),{code:'ECONNRESET'}));
 const expected={throw:'GATEWAY_FORWARD_THROW','request-error':'GATEWAY_UPSTREAM_REQUEST_ERROR',redirect:'GATEWAY_REDIRECT_DENIED',body:'GATEWAY_TRANSPORT_BODY_REJECTED'}[mode];
 assert.equal(rows.at(-1).stage,expected);assert.equal(res.status,502);assert.equal(res.ended,true);assert.equal(journal.attempts,1);
});
