// Assemble a Debian/glibc runtime from vendor-built files, without copying build tools.
// Run only in the installation stage after supported distribution security updates.
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync, spawnSync } = require('node:child_process');
const crypto = require('node:crypto');
const root = '/runtime-root';
const packages = ['libc6', 'libgcc-s1', 'libstdc++6', 'ca-certificates', 'tzdata'];
const copied = new Set();
const copiedRoots = [];
const vendorPackages = new Set(packages);
function ownerOf(source) {
  if (source.startsWith('/app/')) return 'application-and-locked-npm';
  if (source.startsWith('/usr/local/')) return 'official-node-distribution';
  if (source === '/etc/ssl/certs/ca-certificates.crt') return 'ca-certificates';
  const resolved = fs.realpathSync(source);
  const candidates = [...new Set([source, resolved, resolved.replace(/^\/usr\/lib/, '/lib')])];
  const result = candidates.map(file => spawnSync('dpkg-query', ['-S', file], { encoding: 'utf8' })).find(result => result.status === 0);
  if (!result) throw new Error(`No Debian owner for ${source}`);
  const line = result.stdout.trim().split('\n')[0];
  const owner = line.split(': ')[0].replace(/:(arm64|amd64)$/, '');
  vendorPackages.add(owner);
  return owner;
}
function copy(source, destination = source, owner) {
  if (!fs.existsSync(source)) throw new Error(`Missing runtime file: ${source}`);
  const target = path.join(root, destination);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  if (fs.statSync(source).isDirectory()) {
    fs.mkdirSync(target, { recursive: true });
    for (const entry of fs.readdirSync(source)) copy(path.join(source, entry), path.join(destination, entry), owner);
    return;
  }
  owner ||= ownerOf(source);
  fs.cpSync(source, target, { recursive: true, dereference: true });
  copied.add(destination);
  copiedRoots.push({ source, destination, owner });
}
fs.mkdirSync(root, { recursive: true });
// Preserve Debian merged-/usr aliases used by the ELF loader and ldd paths.
for (const name of ['lib', 'lib64']) {
  fs.mkdirSync(`${root}/usr/${name}`, { recursive: true });
  fs.symlinkSync(`usr/${name}`, `${root}/${name}`);
}
for (const name of packages) {
  const files = execFileSync('dpkg-query', ['-L', name], { encoding: 'utf8' }).split('\n');
  for (const file of files) {
    // Keep the shared runtime (including NSS/gconv), never package executables.
    if (/^\/(usr\/)?lib(?:64)?\//.test(file) && (/\.so(?:\.|$)/.test(file) || file.includes('/gconv/')) && fs.existsSync(file)) copy(file);
  }
  copy(`/usr/share/doc/${name}/copyright`);
}
copy('/usr/local/bin/node');
copy('/usr/local/LICENSE', '/usr/share/day-trader/node-LICENSE');
copy('/etc/ssl/certs');
copy('/usr/share/ca-certificates');
copy('/usr/share/zoneinfo');
// Generated by the Debian base's libc installation; not a dpkg-owned file.
copy('/etc/nsswitch.conf', '/etc/nsswitch.conf', 'debian-base-generated-nss-configuration');
copy('/etc/os-release');
copy('/usr/lib/os-release');
copy('/etc/debian_version');
copy('/usr/share/zoneinfo/Etc/UTC', '/etc/localtime');
fs.writeFileSync(`${root}/etc/timezone`, 'Etc/UTC\n');
fs.writeFileSync(`${root}/etc/passwd`, 'node:x:1000:1000:Node service:/nonexistent:/sbin/nologin\n');
fs.writeFileSync(`${root}/etc/group`, 'node:x:1000:\n');
fs.mkdirSync(`${root}/tmp`, { recursive: true, mode: 0o1777 });
fs.chmodSync(`${root}/tmp`, 0o1777);
// Retain source-package/version metadata for every copied Debian runtime package.
// This is an explicit file subset, not a functional dpkg installation.
fs.mkdirSync(`${root}/var/lib/dpkg`, { recursive: true });
fs.writeFileSync(`${root}/var/lib/dpkg/status`, [...vendorPackages].map(name => execFileSync('dpkg-query', ['-s', name], { encoding: 'utf8' }).trim()).join('\n\n') + '\n');
const appEntries = ['package.json', 'node_modules', 'analytics', 'backtest', 'config', 'data', 'middleware', 'models', 'paper', 'robotrader', 'routes', 'services', 'signal', 'utils'];
for (const entry of fs.readdirSync('/app')) if (entry.endsWith('.js')) appEntries.push(entry);
for (const entry of appEntries) copy(`/app/${entry}`);
copy('/app/scripts/bootstrap-owner.js');
function isNative(file) {
  if (file.endsWith('.node')) return true;
  const descriptor = fs.openSync(file, 'r');
  const magic = Buffer.alloc(4);
  try { fs.readSync(descriptor, magic, 0, 4, 0); } finally { fs.closeSync(descriptor); }
  return magic.equals(Buffer.from([0x7f, 0x45, 0x4c, 0x46]));
}
function nativeFiles(directory) {
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap(entry => entry.isDirectory() ? nativeFiles(path.join(directory, entry.name)) : isNative(path.join(directory, entry.name)) ? [path.join(directory, entry.name)] : []);
}
// A future native dependency must have its shared closure reviewed, not silently copied.
const native = nativeFiles(`${root}/app`);
if (native.length) throw new Error(`Review native runtime library closure before release: ${native.join(', ')}`);
const linked = execFileSync('ldd', ['/usr/local/bin/node'], { encoding: 'utf8' });
if (linked.includes('not found')) throw new Error('Missing Node shared dependency');
for (const file of linked.match(/\/[^\s()]+/g) || []) {
  if (!fs.existsSync(path.join(root, file))) throw new Error(`Node runtime closure missing ${file}`);
}
const provenance = {
  distribution: 'Debian Bookworm vendor security packages; selected runtime files only',
  node: process.version, nodeComponents: process.versions,
  nodeSha256: crypto.createHash('sha256').update(fs.readFileSync('/usr/local/bin/node')).digest('hex'),
  packages: [...vendorPackages].map(name => execFileSync('dpkg-query', ['-W', '-f=${Package}\t${Version}\t${Architecture}\n', name], { encoding: 'utf8' }).trim()),
  copiedRoots, nativeAddons: native, nodeDynamicDependencies: linked,
  omitted: ['npm', 'npx', 'corepack', 'yarn', 'perl', 'util-linux', 'apt', 'dpkg executables', 'shells', 'compilers', 'application tests/integration/build/deployment files'],
  maintenance: 'Update the official Node pin and vendor security packages, rebuild, inspect this manifest, test DNS/TLS/timezone/imports/startup, and rescan. No compiled or transplanted security patches.'
};
fs.mkdirSync(`${root}/usr/share/day-trader`, { recursive: true });
function inventory(directory) {
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap(entry => {
    const file = path.join(directory, entry.name), relative = file.slice(root.length);
    if (relative === '/app') return [];
    if (entry.isDirectory()) return inventory(file);
    if (entry.isSymbolicLink()) return [{ path: relative, link: fs.readlinkSync(file) }];
    const origin = copiedRoots.filter(item => relative === item.destination.replace(/^\/lib/, '/usr/lib') || relative.startsWith(item.destination.replace(/^\/lib/, '/usr/lib') + '/')).sort((a,b) => b.destination.length - a.destination.length)[0];
    return [{ path: relative, owner: origin?.owner || 'generated-runtime-configuration', sourceRoot: origin?.source || null, sha256: crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex') }];
  });
}
provenance.exportedFiles = inventory(root);
fs.writeFileSync(`${root}/usr/share/day-trader/runtime-provenance.json`, JSON.stringify(provenance, null, 2) + '\n');
